COHERE_API_KEY = "7TCiEVUlZTXiBPqOAPeuafSdUcGNjtr8n4a7XmgD"
COHERE_MODEL = "command-xlarge-nightly"
COHERE_EMBED_MODEL = "multilingual-22-12"

[server]
# Đường dẫn tương đối đến file chứa ứng dụng Streamlit của bạn
# Ví dụ nếu app của bạn ở trong thư mục src/app.py
headless = true
runOnSave = true
enableCORS = true
enableXsrfProtection = true

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501
